[workspace]

resolver = "2"

members = [
"arch/modules/boot",
"arch/modules/cpu",
"arch/modules/paging",
"arch/modules/serial",
"arch/modules/shutdown",
"lib/kernel-boot-interface",
"lib/kernel-log",
"lib/kernel-test",
"lib/metamorphoses",
"lib/teensy-std",
"kernel",
]

